### ISSUE TITLE
Set up GitHub Actions with RTM and Website combined

### ISSUE THREAD

**Issue by alextac98** [alextac98/dh-viewer#5]
Set up GitHub Actions with RTM and NPM.

## Task Overview
- [ ] Set up GitHub Actions to automatically build website and point to [url]
- [ ] Set up GitHub Actions to automatically build docs and point to [url]/docs/
- [ ] Set up continuous integration
- [ ] Set up a rule to prevent people from merging to main without passing continuous integration

## Overview
Website should be accessible at [url]
Documentation should be accessible at [url]/docs/

GitHub actions should rebuild every time there is a push to the master branch. Therefore, a rule should be set up to prevent pushing to main without a PR
